name: gelir_gider_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  fl_chart: ^0.71.0
  flutter_local_notifications: ^19.1.0
  intl: ^0.20.2
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  csv: ^6.0.0
  excel: ^4.0.6
  file_picker: ^10.1.2
  share_plus: ^11.0.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
