// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9jF2uPcfHngQQoAa9vZGvo0V8radIEEs',
    appId: '1:885441656480:web:80276adb19643604473bc5',
    messagingSenderId: '885441656480',
    projectId: 'mobilfinans-243d5',
    authDomain: 'mobilfinans-243d5.firebaseapp.com',
    storageBucket: 'mobilfinans-243d5.firebasestorage.app',
    measurementId: 'G-FR092K82BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4RaVpudB3EvY14iZmalX3CtA_dY15VvE',
    appId: '1:885441656480:android:e9d89811e0a0f672473bc5',
    messagingSenderId: '885441656480',
    projectId: 'mobilfinans-243d5',
    storageBucket: 'mobilfinans-243d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzHC-Qzo4gIXPuLjiEQN-EbgdUsR8pM48',
    appId: '1:885441656480:ios:87d8e0e5756374d5473bc5',
    messagingSenderId: '885441656480',
    projectId: 'mobilfinans-243d5',
    storageBucket: 'mobilfinans-243d5.firebasestorage.app',
    iosBundleId: 'com.example.gelirGiderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzHC-Qzo4gIXPuLjiEQN-EbgdUsR8pM48',
    appId: '1:885441656480:ios:87d8e0e5756374d5473bc5',
    messagingSenderId: '885441656480',
    projectId: 'mobilfinans-243d5',
    storageBucket: 'mobilfinans-243d5.firebasestorage.app',
    iosBundleId: 'com.example.gelirGiderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9jF2uPcfHngQQoAa9vZGvo0V8radIEEs',
    appId: '1:885441656480:web:bcdffe2ee35d114a473bc5',
    messagingSenderId: '885441656480',
    projectId: 'mobilfinans-243d5',
    authDomain: 'mobilfinans-243d5.firebaseapp.com',
    storageBucket: 'mobilfinans-243d5.firebasestorage.app',
    measurementId: 'G-5JJVPGRC27',
  );
}
